import type { Metadata } from 'next'

import type { General, Media } from '@/payload-types'

import { getCachedGlobal } from './getGlobals'

type Locale = 'en' | 'vi'

type OgImage = { url: string; width?: number; height?: number; alt?: string }

/**
 * Resolves the site logo (from the General global) into an OG image entry.
 * Prefers the 1200×630 `og` size generated by the Media collection, falling
 * back to the original upload.
 */
const resolveLogoOgImage = (general: General | null): OgImage[] | undefined => {
  const logo = general?.logo
  if (!logo || typeof logo !== 'object') return undefined

  const media = logo as Media
  const og = media.sizes?.og
  const url = og?.url ?? media.url
  if (!url) return undefined

  return [
    {
      url,
      width: og?.width ?? media.width ?? undefined,
      height: og?.height ?? media.height ?? undefined,
      alt: media.alt || general?.companyName || undefined,
    },
  ]
}

/**
 * Site-wide default SEO metadata, sourced entirely from the `general` global
 * (General Settings in the admin). Title, description and the OG/Twitter image
 * (the site logo) are all editor-controlled — no code change needed to update SEO.
 */
export const getDefaultSEO = async (locale: Locale): Promise<Metadata> => {
  const general = (await getCachedGlobal('general', 1, locale)()) as General | null

  const siteName = general?.companyName || 'IEC'
  const title = general?.tagline ? `${siteName} — ${general.tagline}` : siteName
  const description = general?.description || undefined
  const images = resolveLogoOgImage(general)

  return {
    title: { default: title, template: `%s | ${siteName}` },
    description,
    openGraph: {
      type: 'website',
      siteName,
      title,
      description,
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: images?.map((i) => i.url),
    },
  }
}

/**
 * Page-level SEO that inherits the site defaults (logo image, siteName, twitter
 * card…) while overriding title/description/url for a specific page.
 *
 * Use this in a page's `generateMetadata` whenever it sets its own `openGraph`,
 * because Next.js replaces (does not deep-merge) the parent `openGraph` — so the
 * logo must be re-supplied here to keep showing in link embeds.
 */
export const buildSEO = async (
  locale: Locale,
  page: { title?: string; description?: string; url?: string; images?: OgImage[] },
): Promise<Metadata> => {
  const base = await getDefaultSEO(locale)
  const baseOg = (base.openGraph ?? {}) as NonNullable<Metadata['openGraph']>
  const baseTw = (base.twitter ?? {}) as NonNullable<Metadata['twitter']>
  const images = page.images ?? baseOg.images

  return {
    ...base,
    title: page.title ?? base.title,
    description: page.description ?? base.description,
    openGraph: {
      ...baseOg,
      title: page.title ?? baseOg.title,
      description: page.description ?? baseOg.description,
      url: page.url,
      images,
    },
    twitter: {
      ...baseTw,
      title: page.title,
      description: page.description ?? base.description,
    },
  }
}
