import type { ComponentType } from 'react'

import {
  IconActivity,
  IconAddressBook,
  IconAlertCircle,
  IconAlertTriangle,
  IconApi,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconAward,
  IconBeach,
  IconBell,
  IconBike,
  IconBolt,
  IconBook,
  IconBooks,
  IconBrain,
  IconBrandDiscord,
  IconBrandFacebook,
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandLinktree,
  IconBrandMessenger,
  IconBrandTelegram,
  IconBrandTiktok,
  IconBrandWhatsapp,
  IconBrandX,
  IconBrandYoutube,
  IconBriefcase,
  IconBrush,
  IconBug,
  IconBuilding,
  IconBuildingCommunity,
  IconBulb,
  IconCake,
  IconCalendar,
  IconCalendarClock,
  IconCalendarEvent,
  IconCar,
  IconCash,
  IconCertificate,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconCheck,
  IconChess,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleX,
  IconClipboard,
  IconClipboardCheck,
  IconClock,
  IconCloud,
  IconCode,
  IconCoffee,
  IconCoin,
  IconConfetti,
  IconCopy,
  IconCpu,
  IconCreditCard,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceGamepad2,
  IconDeviceMobile,
  IconDiscount,
  IconDots,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFileDescription,
  IconFileText,
  IconFiles,
  IconFilter,
  IconFlag,
  IconFlame,
  IconFolder,
  IconFriends,
  IconGift,
  IconGitBranch,
  IconHeadphones,
  IconHeadset,
  IconHeart,
  IconHeartFilled,
  IconHeartHandshake,
  IconHelpCircle,
  IconHourglass,
  IconId,
  IconInfoCircle,
  IconKey,
  IconLeaf,
  IconLink,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMailOpened,
  IconMap,
  IconMapPin,
  IconMenu2,
  IconMessage,
  IconMessageCircle,
  IconMinus,
  IconMoodHappy,
  IconMoodSmile,
  IconMoonStars,
  IconMovie,
  IconMusic,
  IconNotebook,
  IconPalette,
  IconPencil,
  IconPhone,
  IconPhoneCall,
  IconPhoto,
  IconPlane,
  IconPlant,
  IconPlus,
  IconPuzzle,
  IconReceipt,
  IconRefresh,
  IconReport,
  IconRocket,
  IconRun,
  IconSchool,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconShare3,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconSparkles,
  IconStar,
  IconStarFilled,
  IconSun,
  IconTarget,
  IconTerminal,
  IconTrendingUp,
  IconTrophy,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserPlus,
  IconUsers,
  IconVideo,
  IconWallet,
  IconWorld,
  IconX,
  IconZzz,
} from '@tabler/icons-react'

export type TablerIconComponent = ComponentType<{
  size?: number | string
  stroke?: number | string
  color?: string
  className?: string
}>

/**
 * The finite set of Tabler icons editors can pick and the frontend can render.
 *
 * Deliberately NOT a dynamic import keyed by a variable. TablerIcon used to build
 * its import path from the icon name, and a dynamic import whose path contains a
 * variable forces the bundler to emit a chunk for every file matching the glob —
 * all 6,090 icons — plus a name-to-chunk manifest that lands on the page's
 * initial load. Measured on the homepage: 720,691 -> 525,053 bytes gzip once
 * that import was gone, and the chunk count fell from ~6,000 to 95. See
 * plans/260826-1801-frontend-bundle-and-assets/.
 *
 * IconPicker reads this same map, so an editor cannot select an icon the
 * frontend would then fail to render.
 *
 * Keys are kebab-case because that is what the CMS stores.
 *
 * To add an icon: add its kebab-case name to a group below and the matching
 * IconX to the import above. `pnpm exec tsx scripts/collect-cms-icons.ts --check`
 * verifies every name the CMS holds is present here.
 */
export const iconRegistry = {

  // In use on production (from the CMS scan — do not remove without re-scanning)
  'brand-linktree': IconBrandLinktree,
  'heart-handshake': IconHeartHandshake,

  // Navigation & controls
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'arrow-up': IconArrowUp,
  'arrow-down': IconArrowDown,
  'arrow-up-right': IconArrowUpRight,
  'chevron-down': IconChevronDown,
  'chevron-up': IconChevronUp,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'menu-2': IconMenu2,
  'dots': IconDots,
  'x': IconX,
  'plus': IconPlus,
  'minus': IconMinus,
  'search': IconSearch,
  'filter': IconFilter,
  'refresh': IconRefresh,
  'external-link': IconExternalLink,
  'link': IconLink,
  'copy': IconCopy,
  'download': IconDownload,
  'upload': IconUpload,
  'settings': IconSettings,

  // Status & feedback
  'check': IconCheck,
  'circle-check': IconCircleCheck,
  'circle-x': IconCircleX,
  'alert-circle': IconAlertCircle,
  'alert-triangle': IconAlertTriangle,
  'info-circle': IconInfoCircle,
  'help-circle': IconHelpCircle,
  'eye': IconEye,
  'eye-off': IconEyeOff,
  'bell': IconBell,
  'flag': IconFlag,
  'lock': IconLock,
  'lock-open': IconLockOpen,
  'key': IconKey,
  'shield': IconShield,
  'shield-check': IconShieldCheck,
  'shield-lock': IconShieldLock,

  // People & organisation
  'user': IconUser,
  'users': IconUsers,
  'user-plus': IconUserPlus,
  'user-check': IconUserCheck,
  'id': IconId,
  'address-book': IconAddressBook,
  'building': IconBuilding,
  'building-community': IconBuildingCommunity,
  'friends': IconFriends,
  'briefcase': IconBriefcase,

  // Documents & data
  'file-text': IconFileText,
  'file-description': IconFileDescription,
  'files': IconFiles,
  'folder': IconFolder,
  'clipboard': IconClipboard,
  'clipboard-check': IconClipboardCheck,
  'report': IconReport,
  'notebook': IconNotebook,
  'book': IconBook,
  'books': IconBooks,
  'chart-bar': IconChartBar,
  'chart-line': IconChartLine,
  'chart-pie': IconChartPie,
  'database': IconDatabase,
  'server': IconServer,

  // Time & money
  'calendar': IconCalendar,
  'calendar-event': IconCalendarEvent,
  'calendar-clock': IconCalendarClock,
  'clock': IconClock,
  'hourglass': IconHourglass,
  'cash': IconCash,
  'coin': IconCoin,
  'credit-card': IconCreditCard,
  'receipt': IconReceipt,
  'wallet': IconWallet,
  'gift': IconGift,
  'discount': IconDiscount,

  // Communication
  'mail': IconMail,
  'mail-opened': IconMailOpened,
  'message': IconMessage,
  'message-circle': IconMessageCircle,
  'phone': IconPhone,
  'phone-call': IconPhoneCall,
  'headset': IconHeadset,
  'send': IconSend,
  'share-3': IconShare3,
  'world': IconWorld,
  'map-pin': IconMapPin,
  'map': IconMap,

  // Technology & product
  'code': IconCode,
  'terminal': IconTerminal,
  'device-desktop': IconDeviceDesktop,
  'device-mobile': IconDeviceMobile,
  'device-gamepad-2': IconDeviceGamepad2,
  'cpu': IconCpu,
  'cloud': IconCloud,
  'bug': IconBug,
  'git-branch': IconGitBranch,
  'rocket': IconRocket,
  'bolt': IconBolt,
  'api': IconApi,

  // Culture & wellbeing
  'coffee': IconCoffee,
  'cake': IconCake,
  'confetti': IconConfetti,
  'mood-smile': IconMoodSmile,
  'mood-happy': IconMoodHappy,
  'heart': IconHeart,
  'heart-filled': IconHeartFilled,
  'activity': IconActivity,
  'run': IconRun,
  'bike': IconBike,
  'plant': IconPlant,
  'leaf': IconLeaf,
  'sun': IconSun,
  'moon-stars': IconMoonStars,
  'plane': IconPlane,
  'car': IconCar,
  'beach': IconBeach,
  'zzz': IconZzz,

  // Learning & growth
  'school': IconSchool,
  'pencil': IconPencil,
  'edit': IconEdit,
  'bulb': IconBulb,
  'brain': IconBrain,
  'puzzle': IconPuzzle,
  'chess': IconChess,
  'trending-up': IconTrendingUp,
  'certificate': IconCertificate,
  'award': IconAward,
  'trophy': IconTrophy,
  'target': IconTarget,
  'star': IconStar,
  'star-filled': IconStarFilled,
  'sparkles': IconSparkles,
  'flame': IconFlame,
  'palette': IconPalette,
  'brush': IconBrush,
  'photo': IconPhoto,
  'video': IconVideo,
  'music': IconMusic,
  'headphones': IconHeadphones,
  'movie': IconMovie,

  // Brands
  'brand-facebook': IconBrandFacebook,
  'brand-instagram': IconBrandInstagram,
  'brand-linkedin': IconBrandLinkedin,
  'brand-youtube': IconBrandYoutube,
  'brand-tiktok': IconBrandTiktok,
  'brand-x': IconBrandX,
  'brand-telegram': IconBrandTelegram,
  'brand-discord': IconBrandDiscord,
  'brand-whatsapp': IconBrandWhatsapp,
  'brand-messenger': IconBrandMessenger,
  'brand-github': IconBrandGithub,
} satisfies Record<string, TablerIconComponent>

export type RegisteredIconName = keyof typeof iconRegistry

export const registeredIconNames = Object.keys(iconRegistry).sort()

/** Undefined for an unknown name — callers render nothing rather than throwing. */
export function getRegisteredIcon(name: string): TablerIconComponent | undefined {
  return (iconRegistry as Record<string, TablerIconComponent>)[name]
}
