/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    tags: Tag;
    users: User;
    jobs: Job;
    'job-applications': JobApplication;
    social: Social;
    games: Game;
    subscribers: Subscriber;
    'email-campaigns': EmailCampaign;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    social: SocialSelect<false> | SocialSelect<true>;
    games: GamesSelect<false> | GamesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'email-campaigns': EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'vi') | ('en' | 'vi')[];
  globals: {
    header: Header;
    footer: Footer;
    home: Home;
    career: Career;
    general: General;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    career: CareerSelect<false> | CareerSelect<true>;
    general: GeneralSelect<false> | GeneralSelect<true>;
  };
  locale: 'en' | 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'videoHero' | 'brandHero';
    videoSource?: ('upload' | 'youtube') | null;
    videoFile?: (string | null) | Media;
    /**
     * Enter the full YouTube URL (e.g. https://www.youtube.com/watch?v=xxxxx)
     */
    youtubeUrl?: string | null;
    /**
     * Tiêu đề chính hiển thị trong vùng overlay. Phần nằm giữa cặp dấu \\ ... \\ sẽ được highlight (gradient, cỡ chữ lớn, xuống dòng riêng). Ví dụ: "Join us \\IEC Game - Winter Wolf\\" → "IEC Game - Winter Wolf" được highlight. Nếu không có dấu \\, mặc định highlight từ cuối cùng.
     */
    heading?: string | null;
    /**
     * Subtitle / description text below the heading
     */
    subtitle?: string | null;
    /**
     * Content displayed inside the overlay area (left 2/3 of the screen)
     */
    overlayContent?:
      | (CallToActionBlock | ContentBlock | MediaBlock | BannerBlock | CodeBlock | PolicyTabsBlock)[]
      | null;
    primaryButtonLabel?: string | null;
    primaryButtonUrl?: string | null;
    secondaryButtonLabel?: string | null;
    secondaryButtonUrl?: string | null;
    /**
     * YouTube or direct video URL to open in a popup when the play button is clicked
     */
    videoPopupUrl?: string | null;
    /**
     * Small label above the heading (e.g. "Gaming Studio").
     */
    eyebrow?: string | null;
    /**
     * Large brand heading (e.g. "IEC Games").
     */
    brandHeading?: string | null;
    /**
     * Supporting paragraph under the heading.
     */
    tagline?: string | null;
    /**
     * Each stat shows a number that counts up from 0 when scrolled into view, followed by a unit suffix (e.g. value=2.5, suffix="B+", label="Total Downloads" → "2.5B+").
     */
    inlineStats?:
      | {
          /**
           * Numeric value (e.g. 2.5, 50, 20).
           */
          value: number;
          /**
           * Unit / sign appended to the number (e.g. "B+", "M+", "+", "%").
           */
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    mascot?: (string | null) | Media;
    /**
     * Primary call-to-action button (e.g. "Explore us") shown next to the share / video buttons.
     */
    cta?:
      | {
          link: {
            type?: ('reference' | 'route' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            /**
             * Pick a built-in section page (route is hardcoded in the app).
             */
            route?: ('/' | '/posts' | '/career' | '/search') | null;
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Optional. YouTube / Vimeo URL or direct .mp4 link. When set, a play button appears next to the CTA and opens the video in a popup.
     */
    introVideoUrl?: string | null;
    /**
     * QR / share popup next to the CTA. Pick which platforms to expose, an optional centre logo, and a colour preset for the QR code.
     */
    share?: {
      enabledPlatforms?: ('facebook' | 'x' | 'linkedin' | 'messenger' | 'telegram' | 'whatsapp' | 'email')[] | null;
      /**
       * Image rendered at the centre of the QR code (use the site logo). The colour theme of the QR is chosen by the visitor inside the share popup.
       */
      qrLogo?: (string | null) | Media;
    };
    /**
     * Floating 3D / illustrated objects scattered around the hero. Each item has an image, a position, and an optional size %.
     */
    decorations?:
      | {
          image: string | Media;
          position: 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight' | 'middleLeft' | 'middleRight';
          /**
           * Width as % of hero
           */
          sizePercent?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | JobBoardBlock
    | SendUsCVBlock
    | NewsletterSignupBlock
    | AboutWithStatsBlock
    | GamesPortfolioBlock
    | CoreValuesShowcaseBlock
    | CareersHighlightBlock
    | FeatureTabsBlock
    | IECLifeBlock
    | CategoryShowcaseBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'route' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * Pick a built-in section page (route is hardcoded in the app).
           */
          route?: ('/' | '/posts' | '/career' | '/search') | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  tags?: (string | Tag)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  /**
   * Automatically send a promotional email to all subscribers when this post is first published.
   */
  notifySubscribers?: boolean | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'route' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * Pick a built-in section page (route is hardcoded in the app).
           */
          route?: ('/' | '/posts' | '/career' | '/search') | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PolicyTabsBlock".
 */
export interface PolicyTabsBlock {
  tabs?:
    | {
        tabName: string;
        /**
         * Tìm và chọn icon (Tabler) hiển thị trước tên tab.
         */
        icon?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'policyTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JobBoardBlock".
 */
export interface JobBoardBlock {
  heading?: string | null;
  subtitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'jobBoard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SendUsCVBlock".
 */
export interface SendUsCVBlock {
  heading?: string | null;
  subtitle?: string | null;
  /**
   * Link for the "Send Us Your CV" button
   */
  cvUrl?: string | null;
  innovatorLabel?: string | null;
  innovatorAvatars?:
    | {
        avatar: string | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sendUsCV';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock".
 */
export interface NewsletterSignupBlock {
  /**
   * Small label above the heading, e.g. "Stay in the loop"
   */
  eyebrow?: string | null;
  heading: string;
  subtitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletterSignup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutWithStatsBlock".
 */
export interface AboutWithStatsBlock {
  /**
   * Optional horizontal scrolling text strip at the top of the section. Each phrase is rendered in a row separated by the badge image, and the whole row translates sideways as the user scrolls through the section.
   */
  marqueePhrases?:
    | {
        /**
         * Short uppercase phrase (e.g. "CHẤT LƯỢNG").
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Badge image displayed between marquee phrases (e.g. a circular "IEC GAMES STUDIO" stamp). Only shown when Marquee Phrases is configured.
   */
  marqueeBadge?: (string | null) | Media;
  /**
   * Small uppercase label above the heading (e.g. "IEC GAMES LÀ STUDIO").
   */
  eyebrow?: string | null;
  /**
   * Bolded words/phrases will be rendered with the brand gradient color.
   */
  heading: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image or video displayed beside the description. If a video is uploaded, it will not autoplay — a play button appears on hover.
   */
  supportImage?: (string | null) | Media;
  /**
   * Select whether to upload a video file or paste a YouTube link for the right column.
   */
  featureVideoSource?: ('upload' | 'youtube') | null;
  /**
   * Upload a video or image file to display in the right column.
   */
  featureVideo?: (string | null) | Media;
  /**
   * Paste any YouTube URL (watch, share, or embed). Autoplays muted when scrolled into view.
   */
  featureVideoYoutubeUrl?: string | null;
  /**
   * Optional second mascot (e.g. a mascot in an airplane) that flies across the section as the user scrolls — enters from one side, arcs through the middle, exits on the other side.
   */
  flyingMascot?: (string | null) | Media;
  /**
   * Optional "Về [Studio]" link rendered under the description with an arrow.
   */
  cta?:
    | {
        link: {
          type?: ('reference' | 'route' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * Pick a built-in section page (route is hardcoded in the app).
           */
          route?: ('/' | '/posts' | '/career' | '/search') | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Each stat counts up from 0 when scrolled into view. e.g. value=50, suffix="+", label="Nhân sự chuyên nghiệp".
   */
  stats?:
    | {
        /**
         * Numeric value (e.g. 50, 5, 20).
         */
        value: number;
        /**
         * Unit / sign appended to the number (e.g. "+", "M+", "%").
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional floating 3D / illustrated objects scattered around the section.
   */
  decorations?:
    | {
        image: string | Media;
        position: 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight' | 'middleLeft' | 'middleRight';
        /**
         * Width as % of section
         */
        sizePercent?: number | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutWithStats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GamesPortfolioBlock".
 */
export interface GamesPortfolioBlock {
  eyebrow?: string | null;
  heading: string;
  populateBy?: ('collection' | 'selection') | null;
  selectedGames?: (string | Game)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gamesPortfolio';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games".
 */
export interface Game {
  id: string;
  title: string;
  cover: string | Media;
  /**
   * Short tagline shown under the title on portfolio cards.
   */
  description?: string | null;
  /**
   * Short pills shown on the card (e.g. "18+", "TOP 10", "200+ Downloads").
   */
  badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * External link to play / download the game.
   */
  playUrl?: string | null;
  /**
   * Apple App Store link.
   */
  appStoreUrl?: string | null;
  /**
   * Google Play Store link.
   */
  googlePlayUrl?: string | null;
  /**
   * Số lượt tải hiển thị trên card (ví dụ: "10M+", "500K+").
   */
  downloads?: string | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesShowcaseBlock".
 */
export interface CoreValuesShowcaseBlock {
  /**
   * Small label shown in the pill above the heading.
   */
  eyebrow?: string | null;
  eyebrowIcon?:
    | (
        | 'sparkles'
        | 'diamond'
        | 'sleep'
        | 'gamepad'
        | 'heart'
        | 'star'
        | 'users'
        | 'shield'
        | 'trophy'
        | 'bolt'
        | 'target'
        | 'palette'
        | 'rocket'
        | 'eye'
        | 'flame'
        | 'coffee'
      )
    | null;
  /**
   * Any "&" is highlighted in primary color.
   */
  heading: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Small feature pills shown below the body.
   */
  features?:
    | {
        icon?:
          | (
              | 'sparkles'
              | 'diamond'
              | 'sleep'
              | 'gamepad'
              | 'heart'
              | 'star'
              | 'users'
              | 'shield'
              | 'trophy'
              | 'bolt'
              | 'target'
              | 'palette'
              | 'rocket'
              | 'eye'
              | 'flame'
              | 'coffee'
            )
          | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  vision?: string | null;
  mission?: string | null;
  /**
   * Character shown in the center of the scroll animation.
   */
  mascot?: (string | null) | Media;
  valuesEyebrow?: string | null;
  /**
   * Short subtitle shown below the Core Values heading.
   */
  valuesDescription?: string | null;
  values?:
    | {
        icon?:
          | (
              | 'sparkles'
              | 'diamond'
              | 'sleep'
              | 'gamepad'
              | 'heart'
              | 'star'
              | 'users'
              | 'shield'
              | 'trophy'
              | 'bolt'
              | 'target'
              | 'palette'
              | 'rocket'
              | 'eye'
              | 'flame'
              | 'coffee'
            )
          | null;
        title: string;
        description?: string | null;
        /**
         * Image revealed when this card is hovered/expanded.
         */
        image?: (string | null) | Media;
        /**
         * Caption shown below the expanded image.
         */
        imageCaption?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?:
    | {
        link: {
          type?: ('reference' | 'route' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * Pick a built-in section page (route is hardcoded in the app).
           */
          route?: ('/' | '/posts' | '/career' | '/search') | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'coreValuesShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CareersHighlightBlock".
 */
export interface CareersHighlightBlock {
  /**
   * Small uppercase label shown above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Words from the heading that should be rendered in the primary color (must match the suffix of the heading).
   */
  headingHighlight?: string | null;
  description?: string | null;
  /**
   * Decorative illustration shown on the right side of the section.
   */
  heroImage?: (string | null) | Media;
  /**
   * How many featured jobs to show (jobs with "Featured Job" enabled).
   */
  limit?: number | null;
  ctaLabel?: string | null;
  ctaLink?: {
    type?: ('reference' | 'route' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    /**
     * Pick a built-in section page (route is hardcoded in the app).
     */
    route?: ('/' | '/posts' | '/career' | '/search') | null;
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'careersHighlight';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureTabsBlock".
 */
export interface FeatureTabsBlock {
  tabs?:
    | {
        label: string;
        icon?: (string | null) | Media;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IECLifeBlock".
 */
export interface IECLifeBlock {
  eyebrow?: string | null;
  heading: string;
  ctaLabel?: string | null;
  /**
   * How many recent posts to show (1 featured + the rest in the side list).
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iecLife';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryShowcaseBlock".
 */
export interface CategoryShowcaseBlock {
  /**
   * Small uppercase label shown above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Only posts in this category will be shown in the block.
   */
  category: string | Category;
  /**
   * Label for the dark CTA button under the description.
   */
  ctaLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  title: string;
  /**
   * Show this job in the CareersHighlight block on the home page.
   */
  isFeatured?: boolean | null;
  /**
   * Manually pin up to 3 related jobs shown at the bottom of this posting. Leave empty to auto-suggest jobs from the same department.
   */
  relatedJobs?: (string | Job)[] | null;
  /**
   * Automatically send a promotional email to all subscribers when this job is first published.
   */
  notifySubscribers?: boolean | null;
  department: string;
  location: string;
  employmentType?: ('fullTime' | 'partTime' | 'contract' | 'internship') | null;
  /**
   * e.g. "9AM – 6PM, Mon–Fri"
   */
  workingHours?: string | null;
  /**
   * e.g. "Competitive" or "$80k–$120k"
   */
  salaryLabel?: string | null;
  linkedinUrl?: string | null;
  /**
   * One-paragraph summary shown under the title on the detail page.
   */
  description?: string | null;
  jobDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  qualifications?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  /**
   * The job this application was submitted for. Empty means a general/open application.
   */
  job?: (string | null) | Job;
  /**
   * Position the candidate is interested in. Auto-filled from the job title for job-specific applications.
   */
  position?: string | null;
  experience?: string | null;
  /**
   * Portfolio, product showcase, GitHub, Behance, or other relevant link.
   */
  additionalLink?: string | null;
  cv: string | Media;
  status?: ('new' | 'reviewing' | 'contacted' | 'rejected' | 'hired') | null;
  submittedAt?: string | null;
  /**
   * HR-only notes about this candidate.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social".
 */
export interface Social {
  id: string;
  platform: 'linkedin' | 'facebook' | 'instagram' | 'youtube' | 'twitter' | 'tiktok' | 'discord';
  url: string;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: string;
  email: string;
  name?: string | null;
  source?: ('job_application' | 'form_submission' | 'newsletter') | null;
  subscribed?: boolean | null;
  unsubscribeToken?: string | null;
  subscribedAt?: string | null;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns".
 */
export interface EmailCampaign {
  id: string;
  name: string;
  /**
   * Supports tokens: {{job.title}}, {{post.title}}
   */
  subject: string;
  /**
   * Short preview text shown in email clients
   */
  previewText?: string | null;
  type: 'manual' | 'new_job' | 'new_post';
  /**
   * Required for Manual campaigns. Optional for New Job / New Post — leave empty to use the default template. Available tokens: {{post.title}}, {{post.url}}, {{post.excerpt}}, {{job.title}}, {{job.url}}, {{subscriber.name}}
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedJob?: (string | null) | Job;
  relatedPost?: (string | null) | Post;
  status?: ('draft' | 'sending' | 'sent') | null;
  sentAt?: string | null;
  recipientCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        relationTo?: string | null;
        tagID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'jobs';
        value: string | Job;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: string | JobApplication;
      } | null)
    | ({
        relationTo: 'social';
        value: string | Social;
      } | null)
    | ({
        relationTo: 'games';
        value: string | Game;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: string | Subscriber;
      } | null)
    | ({
        relationTo: 'email-campaigns';
        value: string | EmailCampaign;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        videoSource?: T;
        videoFile?: T;
        youtubeUrl?: T;
        heading?: T;
        subtitle?: T;
        overlayContent?:
          | T
          | {
              cta?: T | CallToActionBlockSelect<T>;
              content?: T | ContentBlockSelect<T>;
              mediaBlock?: T | MediaBlockSelect<T>;
              banner?: T | BannerBlockSelect<T>;
              code?: T | CodeBlockSelect<T>;
              policyTabs?: T | PolicyTabsBlockSelect<T>;
            };
        primaryButtonLabel?: T;
        primaryButtonUrl?: T;
        secondaryButtonLabel?: T;
        secondaryButtonUrl?: T;
        videoPopupUrl?: T;
        eyebrow?: T;
        brandHeading?: T;
        tagline?: T;
        inlineStats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        mascot?: T;
        cta?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    route?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        introVideoUrl?: T;
        share?:
          | T
          | {
              enabledPlatforms?: T;
              qrLogo?: T;
            };
        decorations?:
          | T
          | {
              image?: T;
              position?: T;
              sizePercent?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        jobBoard?: T | JobBoardBlockSelect<T>;
        sendUsCV?: T | SendUsCVBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        aboutWithStats?: T | AboutWithStatsBlockSelect<T>;
        gamesPortfolio?: T | GamesPortfolioBlockSelect<T>;
        coreValuesShowcase?: T | CoreValuesShowcaseBlockSelect<T>;
        careersHighlight?: T | CareersHighlightBlockSelect<T>;
        featureTabs?: T | FeatureTabsBlockSelect<T>;
        iecLife?: T | IECLifeBlockSelect<T>;
        categoryShowcase?: T | CategoryShowcaseBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              route?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              route?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PolicyTabsBlock_select".
 */
export interface PolicyTabsBlockSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        tabName?: T;
        icon?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JobBoardBlock_select".
 */
export interface JobBoardBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SendUsCVBlock_select".
 */
export interface SendUsCVBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  cvUrl?: T;
  innovatorLabel?: T;
  innovatorAvatars?:
    | T
    | {
        avatar?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterSignupBlock_select".
 */
export interface NewsletterSignupBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutWithStatsBlock_select".
 */
export interface AboutWithStatsBlockSelect<T extends boolean = true> {
  marqueePhrases?:
    | T
    | {
        text?: T;
        id?: T;
      };
  marqueeBadge?: T;
  eyebrow?: T;
  heading?: T;
  description?: T;
  supportImage?: T;
  featureVideoSource?: T;
  featureVideo?: T;
  featureVideoYoutubeUrl?: T;
  flyingMascot?: T;
  cta?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              route?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  decorations?:
    | T
    | {
        image?: T;
        position?: T;
        sizePercent?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GamesPortfolioBlock_select".
 */
export interface GamesPortfolioBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  populateBy?: T;
  selectedGames?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreValuesShowcaseBlock_select".
 */
export interface CoreValuesShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  eyebrowIcon?: T;
  heading?: T;
  body?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  vision?: T;
  mission?: T;
  mascot?: T;
  valuesEyebrow?: T;
  valuesDescription?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        image?: T;
        imageCaption?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              route?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CareersHighlightBlock_select".
 */
export interface CareersHighlightBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  headingHighlight?: T;
  description?: T;
  heroImage?: T;
  limit?: T;
  ctaLabel?: T;
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        route?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureTabsBlock_select".
 */
export interface FeatureTabsBlockSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        label?: T;
        icon?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IECLifeBlock_select".
 */
export interface IECLifeBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  ctaLabel?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryShowcaseBlock_select".
 */
export interface CategoryShowcaseBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  category?: T;
  ctaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  notifySubscribers?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  isFeatured?: T;
  relatedJobs?: T;
  notifySubscribers?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  workingHours?: T;
  salaryLabel?: T;
  linkedinUrl?: T;
  description?: T;
  jobDescription?: T;
  qualifications?: T;
  benefits?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  job?: T;
  position?: T;
  experience?: T;
  additionalLink?: T;
  cv?: T;
  status?: T;
  submittedAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_select".
 */
export interface SocialSelect<T extends boolean = true> {
  platform?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "games_select".
 */
export interface GamesSelect<T extends boolean = true> {
  title?: T;
  cover?: T;
  description?: T;
  badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  playUrl?: T;
  appStoreUrl?: T;
  googlePlayUrl?: T;
  downloads?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  source?: T;
  subscribed?: T;
  unsubscribeToken?: T;
  subscribedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-campaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  name?: T;
  subject?: T;
  previewText?: T;
  type?: T;
  body?: T;
  relatedJob?: T;
  relatedPost?: T;
  status?: T;
  sentAt?: T;
  recipientCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        relationTo?: T;
        tagID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'route' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * Pick a built-in section page (route is hardcoded in the app).
           */
          route?: ('/' | '/posts' | '/career' | '/search') | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  companyName?: string | null;
  address?: string | null;
  hotline?: string | null;
  email?: string | null;
  /**
   * Short tagline displayed under the logo in the footer
   */
  logoSubtitle?: string | null;
  phone?: string | null;
  phoneUrl?: string | null;
  copyright?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'route' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          /**
           * Pick a built-in section page (route is hardcoded in the app).
           */
          route?: ('/' | '/posts' | '/career' | '/search') | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero: {
    type: 'none' | 'videoHero' | 'brandHero';
    videoSource?: ('upload' | 'youtube') | null;
    videoFile?: (string | null) | Media;
    /**
     * Enter the full YouTube URL (e.g. https://www.youtube.com/watch?v=xxxxx)
     */
    youtubeUrl?: string | null;
    /**
     * Tiêu đề chính hiển thị trong vùng overlay. Phần nằm giữa cặp dấu \\ ... \\ sẽ được highlight (gradient, cỡ chữ lớn, xuống dòng riêng). Ví dụ: "Join us \\IEC Game - Winter Wolf\\" → "IEC Game - Winter Wolf" được highlight. Nếu không có dấu \\, mặc định highlight từ cuối cùng.
     */
    heading?: string | null;
    /**
     * Subtitle / description text below the heading
     */
    subtitle?: string | null;
    /**
     * Content displayed inside the overlay area (left 2/3 of the screen)
     */
    overlayContent?:
      | (CallToActionBlock | ContentBlock | MediaBlock | BannerBlock | CodeBlock | PolicyTabsBlock)[]
      | null;
    primaryButtonLabel?: string | null;
    primaryButtonUrl?: string | null;
    secondaryButtonLabel?: string | null;
    secondaryButtonUrl?: string | null;
    /**
     * YouTube or direct video URL to open in a popup when the play button is clicked
     */
    videoPopupUrl?: string | null;
    /**
     * Small label above the heading (e.g. "Gaming Studio").
     */
    eyebrow?: string | null;
    /**
     * Large brand heading (e.g. "IEC Games").
     */
    brandHeading?: string | null;
    /**
     * Supporting paragraph under the heading.
     */
    tagline?: string | null;
    /**
     * Each stat shows a number that counts up from 0 when scrolled into view, followed by a unit suffix (e.g. value=2.5, suffix="B+", label="Total Downloads" → "2.5B+").
     */
    inlineStats?:
      | {
          /**
           * Numeric value (e.g. 2.5, 50, 20).
           */
          value: number;
          /**
           * Unit / sign appended to the number (e.g. "B+", "M+", "+", "%").
           */
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    mascot?: (string | null) | Media;
    /**
     * Primary call-to-action button (e.g. "Explore us") shown next to the share / video buttons.
     */
    cta?:
      | {
          link: {
            type?: ('reference' | 'route' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            /**
             * Pick a built-in section page (route is hardcoded in the app).
             */
            route?: ('/' | '/posts' | '/career' | '/search') | null;
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Optional. YouTube / Vimeo URL or direct .mp4 link. When set, a play button appears next to the CTA and opens the video in a popup.
     */
    introVideoUrl?: string | null;
    /**
     * QR / share popup next to the CTA. Pick which platforms to expose, an optional centre logo, and a colour preset for the QR code.
     */
    share?: {
      enabledPlatforms?: ('facebook' | 'x' | 'linkedin' | 'messenger' | 'telegram' | 'whatsapp' | 'email')[] | null;
      /**
       * Image rendered at the centre of the QR code (use the site logo). The colour theme of the QR is chosen by the visitor inside the share popup.
       */
      qrLogo?: (string | null) | Media;
    };
    /**
     * Floating 3D / illustrated objects scattered around the hero. Each item has an image, a position, and an optional size %.
     */
    decorations?:
      | {
          image: string | Media;
          position: 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight' | 'middleLeft' | 'middleRight';
          /**
           * Width as % of hero
           */
          sizePercent?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
        | JobBoardBlock
        | SendUsCVBlock
        | NewsletterSignupBlock
        | AboutWithStatsBlock
        | GamesPortfolioBlock
        | CoreValuesShowcaseBlock
        | CareersHighlightBlock
        | FeatureTabsBlock
        | IECLifeBlock
        | CategoryShowcaseBlock
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career".
 */
export interface Career {
  id: string;
  hero: {
    type: 'none' | 'videoHero' | 'brandHero';
    videoSource?: ('upload' | 'youtube') | null;
    videoFile?: (string | null) | Media;
    /**
     * Enter the full YouTube URL (e.g. https://www.youtube.com/watch?v=xxxxx)
     */
    youtubeUrl?: string | null;
    /**
     * Tiêu đề chính hiển thị trong vùng overlay. Phần nằm giữa cặp dấu \\ ... \\ sẽ được highlight (gradient, cỡ chữ lớn, xuống dòng riêng). Ví dụ: "Join us \\IEC Game - Winter Wolf\\" → "IEC Game - Winter Wolf" được highlight. Nếu không có dấu \\, mặc định highlight từ cuối cùng.
     */
    heading?: string | null;
    /**
     * Subtitle / description text below the heading
     */
    subtitle?: string | null;
    /**
     * Content displayed inside the overlay area (left 2/3 of the screen)
     */
    overlayContent?:
      | (CallToActionBlock | ContentBlock | MediaBlock | BannerBlock | CodeBlock | PolicyTabsBlock)[]
      | null;
    primaryButtonLabel?: string | null;
    primaryButtonUrl?: string | null;
    secondaryButtonLabel?: string | null;
    secondaryButtonUrl?: string | null;
    /**
     * YouTube or direct video URL to open in a popup when the play button is clicked
     */
    videoPopupUrl?: string | null;
    /**
     * Small label above the heading (e.g. "Gaming Studio").
     */
    eyebrow?: string | null;
    /**
     * Large brand heading (e.g. "IEC Games").
     */
    brandHeading?: string | null;
    /**
     * Supporting paragraph under the heading.
     */
    tagline?: string | null;
    /**
     * Each stat shows a number that counts up from 0 when scrolled into view, followed by a unit suffix (e.g. value=2.5, suffix="B+", label="Total Downloads" → "2.5B+").
     */
    inlineStats?:
      | {
          /**
           * Numeric value (e.g. 2.5, 50, 20).
           */
          value: number;
          /**
           * Unit / sign appended to the number (e.g. "B+", "M+", "+", "%").
           */
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    mascot?: (string | null) | Media;
    /**
     * Primary call-to-action button (e.g. "Explore us") shown next to the share / video buttons.
     */
    cta?:
      | {
          link: {
            type?: ('reference' | 'route' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            /**
             * Pick a built-in section page (route is hardcoded in the app).
             */
            route?: ('/' | '/posts' | '/career' | '/search') | null;
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Optional. YouTube / Vimeo URL or direct .mp4 link. When set, a play button appears next to the CTA and opens the video in a popup.
     */
    introVideoUrl?: string | null;
    /**
     * QR / share popup next to the CTA. Pick which platforms to expose, an optional centre logo, and a colour preset for the QR code.
     */
    share?: {
      enabledPlatforms?: ('facebook' | 'x' | 'linkedin' | 'messenger' | 'telegram' | 'whatsapp' | 'email')[] | null;
      /**
       * Image rendered at the centre of the QR code (use the site logo). The colour theme of the QR is chosen by the visitor inside the share popup.
       */
      qrLogo?: (string | null) | Media;
    };
    /**
     * Floating 3D / illustrated objects scattered around the hero. Each item has an image, a position, and an optional size %.
     */
    decorations?:
      | {
          image: string | Media;
          position: 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight' | 'middleLeft' | 'middleRight';
          /**
           * Width as % of hero
           */
          sizePercent?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | CallToActionBlock
        | ContentBlock
        | MediaBlock
        | ArchiveBlock
        | FormBlock
        | JobBoardBlock
        | SendUsCVBlock
        | NewsletterSignupBlock
        | AboutWithStatsBlock
        | GamesPortfolioBlock
        | CoreValuesShowcaseBlock
        | CareersHighlightBlock
        | FeatureTabsBlock
        | IECLifeBlock
        | CategoryShowcaseBlock
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general".
 */
export interface General {
  id: string;
  /**
   * Used in emails, browser tab, and meta tags.
   */
  companyName: string;
  /**
   * Main logo displayed in the header and emails.
   */
  logo?: (string | null) | Media;
  /**
   * Browser tab icon. Recommended: 32×32 or 64×64 PNG/ICO.
   */
  favicon?: (string | null) | Media;
  /**
   * Short slogan displayed under the logo or in meta tags.
   */
  tagline?: string | null;
  /**
   * Default meta description for SEO. Keep under 160 characters.
   */
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              route?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  companyName?: T;
  address?: T;
  hotline?: T;
  email?: T;
  logoSubtitle?: T;
  phone?: T;
  phoneUrl?: T;
  copyright?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              route?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        type?: T;
        videoSource?: T;
        videoFile?: T;
        youtubeUrl?: T;
        heading?: T;
        subtitle?: T;
        overlayContent?:
          | T
          | {
              cta?: T | CallToActionBlockSelect<T>;
              content?: T | ContentBlockSelect<T>;
              mediaBlock?: T | MediaBlockSelect<T>;
              banner?: T | BannerBlockSelect<T>;
              code?: T | CodeBlockSelect<T>;
              policyTabs?: T | PolicyTabsBlockSelect<T>;
            };
        primaryButtonLabel?: T;
        primaryButtonUrl?: T;
        secondaryButtonLabel?: T;
        secondaryButtonUrl?: T;
        videoPopupUrl?: T;
        eyebrow?: T;
        brandHeading?: T;
        tagline?: T;
        inlineStats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        mascot?: T;
        cta?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    route?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        introVideoUrl?: T;
        share?:
          | T
          | {
              enabledPlatforms?: T;
              qrLogo?: T;
            };
        decorations?:
          | T
          | {
              image?: T;
              position?: T;
              sizePercent?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        jobBoard?: T | JobBoardBlockSelect<T>;
        sendUsCV?: T | SendUsCVBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        aboutWithStats?: T | AboutWithStatsBlockSelect<T>;
        gamesPortfolio?: T | GamesPortfolioBlockSelect<T>;
        coreValuesShowcase?: T | CoreValuesShowcaseBlockSelect<T>;
        careersHighlight?: T | CareersHighlightBlockSelect<T>;
        featureTabs?: T | FeatureTabsBlockSelect<T>;
        iecLife?: T | IECLifeBlockSelect<T>;
        categoryShowcase?: T | CategoryShowcaseBlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career_select".
 */
export interface CareerSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        type?: T;
        videoSource?: T;
        videoFile?: T;
        youtubeUrl?: T;
        heading?: T;
        subtitle?: T;
        overlayContent?:
          | T
          | {
              cta?: T | CallToActionBlockSelect<T>;
              content?: T | ContentBlockSelect<T>;
              mediaBlock?: T | MediaBlockSelect<T>;
              banner?: T | BannerBlockSelect<T>;
              code?: T | CodeBlockSelect<T>;
              policyTabs?: T | PolicyTabsBlockSelect<T>;
            };
        primaryButtonLabel?: T;
        primaryButtonUrl?: T;
        secondaryButtonLabel?: T;
        secondaryButtonUrl?: T;
        videoPopupUrl?: T;
        eyebrow?: T;
        brandHeading?: T;
        tagline?: T;
        inlineStats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        mascot?: T;
        cta?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    route?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        introVideoUrl?: T;
        share?:
          | T
          | {
              enabledPlatforms?: T;
              qrLogo?: T;
            };
        decorations?:
          | T
          | {
              image?: T;
              position?: T;
              sizePercent?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        jobBoard?: T | JobBoardBlockSelect<T>;
        sendUsCV?: T | SendUsCVBlockSelect<T>;
        newsletterSignup?: T | NewsletterSignupBlockSelect<T>;
        aboutWithStats?: T | AboutWithStatsBlockSelect<T>;
        gamesPortfolio?: T | GamesPortfolioBlockSelect<T>;
        coreValuesShowcase?: T | CoreValuesShowcaseBlockSelect<T>;
        careersHighlight?: T | CareersHighlightBlockSelect<T>;
        featureTabs?: T | FeatureTabsBlockSelect<T>;
        iecLife?: T | IECLifeBlockSelect<T>;
        categoryShowcase?: T | CategoryShowcaseBlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general_select".
 */
export interface GeneralSelect<T extends boolean = true> {
  companyName?: T;
  logo?: T;
  favicon?: T;
  tagline?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}